// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HelloWebAPI.EmployeeModels
{
    public partial class Employee
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public decimal? salary { get; set; }
        public DateTime? joiningdate { get; set; }
        public int dept_id { get; set; }
    }
}